workflows:
  ios-debug:
    name: iOS Debug
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
